version: '3'

services:
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        container_name: diploma_app
        volumes:
            - ./:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - pgsql

    nginx:
        image: nginx:1.21
        container_name: diploma_nginx
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/:/etc/nginx/conf.d
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - app

    pgsql:
        image: postgres:13.3
        container_name: diploma_postgres
        environment:
            POSTGRES_DB: ${DB_DATABASE:-db_name}
            POSTGRES_USER: ${DB_USERNAME:-user}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        restart: always
